### ISSUE TITLE
Sxhkd !button deprecated

### ISSUE THREAD

**Issue by derrickcope** [wmutils/contrib#32]
Sxhkd no longer works for moving the focused window with the mouse. I think. Is there a workaround? I can use the keyboard but sometimes I am just in a hurry.

**Comment by z3bra** [comment]
This is definitely not an issue that wmutils has to deal with. There is an `xmmv` tool in the [opt/](https://github.com/wmutils/opt/blob/master/xmmv.c) repo that has been around for a really long time and works perfectly for this purpose.

If you insist on relying on sxhkd to move window, you need to take a look at how window moving is handled by sxhkd. Because even though it's a "generic" tool, it is written with bspwm usability in mind.
Support for the `!button` was removed per commit https://github.com/baskerville/sxhkd/commit/0
/07595089fee6aac5953af8acb2f2e98682fa03d5. It was replaced by a socket sxhkd is writting coordinates to. You can have a script use this socket to start moving windows around upon mouse button down, and stop moving on mouse button up (using the `@` modifier).

**Comment by derrickcope** [comment]
Thank you for the answer. Btw, loving wmutils.

**Comment by Anachron** [comment]
Maybe a little late, but if I get it correctly it will just pipe into `"/tmp/bspwm%s_%i_%i-socket"` (coming from) https://github.com/baskerville/sxhkd/commit/07595089fee6aac5953af8acb2f2e98682fa03d5#diff-223ed1dcd8fa9f38d64cdf55a17b925cR40 instead of handling the action directly. 

The new line in the example looks like: https://github.com/baskerville/sxhkd/commit/07595089fee6aac5953af8acb2f2e98682fa03d5#diff-df1059a3386691b6f923532f51843728R151

**Comment by z3bra** [comment]
Yeah that's what I said 2 monthes ago.

**Comment by Anachron** [comment]
@z3bratabs well I was mostly trying to supply a little more information in case I need it later :+1: 
I'm about to switch my main OS to wmutils.
