### ISSUE TITLE
focus.sh previous window

### ISSUE THREAD

**Issue by Vouivre** [wmutils/contrib#4]
Hello, when the script focus.sh with the arguments next is used, the next window in the stack is focused. With it we can cycle through each windows. When focus.sh is used with the prev argument, we can only switch between the two windows on the top of the stack. We can't cycle in the other direction. Is it a bug or a feature ? I Would like to cycle in the reverse direction of "focus.sh next".

**Comment by z3bra** [comment]
Hi, it is not a bug. This behavior is due to how the script works. Xorg lists the windows in their stacking order (from the one on top of all the others, to the one in the bottom). When you focus a window, the script will put it on top of the stack, making it the first of the list, and putting the last focused window in the 2nd position of the stack. To focus the "next" window, the script take the window at the bottom of the stack, and make it first (putting the last focused window in the 2nd place). To focus the "prev" window, we take the second window in the list, and make it first. so focusing the previous window will always alternate between the windows in place 1 and 2 of the stack, no matter what. To reproduce the behavior your talking about, we should remember the whole list of windows, keep it updated upon each call, attribute a number to each window, and sort them on each call to focus them in a specific order. I find it way to complex for such a simple task, so I just always cycle "next", and use "prev" to switch back to the last used window only.

If you can think of a simple and nice way to "reverse-cycle", I would welcome the patch. But I couldn't find it myself, sorry

**Comment by Vouivre** [comment]
Thank you for the explanation! Now I know it's the way it works and I must find a way to code it differently if I want the process I described. I must say it's also practical to be able to switch between the applications on top of the stack.

**Comment by greduan** [comment]
I don't feel like it'd be particularly hard to have a file that keeps track of the order in which windows have been switched. In fact it's actually pretty easy, if I'm thinking of this correctly.

You just need the focus script have a file somewhere where it keeps track of windows and for it to do the following:

Find the window that is being switched to (pfw most probably), delete it from that file and then add it again at the bottom.

And with that you just read the file in reverse (from bottom to top) to know which window was switched to recently. Shouldn't be too difficult. :)
